# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 09:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='EducationDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_degrees', to='companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default='', max_length=12)),
                ('last_name', models.CharField(blank=True, default='', max_length=12)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('id_number', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('field_of_study', models.CharField(max_length=255)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.Branch')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.Company')),
                ('contract_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.Contract')),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.Degree')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.Department')),
                ('education_degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.EducationDegree')),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genders', to='companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='IdDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_documents', to='companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='MilitaryStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='military_status', to='companies.Company')),
            ],
            options={
                'verbose_name_plural': 'Military status',
            },
        ),
        migrations.CreateModel(
            name='Religion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='religions', to='companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='SocialStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=12)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_status', to='companies.Company')),
            ],
            options={
                'verbose_name_plural': 'Social status',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.Gender'),
        ),
        migrations.AddField(
            model_name='employee',
            name='id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.IdDocument'),
        ),
        migrations.AddField(
            model_name='employee',
            name='military_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.MilitaryStatus'),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_employees', to='countries.Nationality'),
        ),
        migrations.AddField(
            model_name='employee',
            name='place_of_birth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='born_in_employees', to='countries.City'),
        ),
        migrations.AddField(
            model_name='employee',
            name='religion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.Religion'),
        ),
        migrations.AddField(
            model_name='employee',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.Section'),
        ),
        migrations.AddField(
            model_name='employee',
            name='social_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.SocialStatus'),
        ),
        migrations.AddField(
            model_name='employee',
            name='sub_section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='companies.SubSection'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='socialstatus',
            unique_together=set([('name', 'company_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='religion',
            unique_together=set([('name', 'company_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='militarystatus',
            unique_together=set([('name', 'company_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='iddocument',
            unique_together=set([('name', 'company_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='gender',
            unique_together=set([('name', 'company_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set([('id_number', 'company_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='educationdegree',
            unique_together=set([('name', 'company_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together=set([('name', 'company_id')]),
        ),
    ]
