# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-30 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20180530_0830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.IdDocument'),
            preserve_default=False,
        ),
    ]
