# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-25 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_hiring',
            field=models.DateField(blank=True, null=True),
        ),
    ]
