# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0009_auto_20180626_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set([('email', 'company_id'), ('employee_number', 'company_id'), ('id_number', 'company_id')]),
        ),
    ]
