# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0010_auto_20180627_1040'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set([('email', 'company_id'), ('id_number', 'company_id')]),
        ),
    ]
