# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_auto_20180627_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_number',
        ),
    ]
