# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('employees', '0012_remove_employee_employee_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set([('id_number', 'company_id'), ('employee_number', 'company_id'), ('email', 'company_id')]),
        ),
    ]
