# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='companies.Company')),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('company', 'Company account'), ('employee', 'Employee account')], max_length=20)),
                ('account_number', models.CharField(max_length=255)),
                ('account_company_holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='companies.Company')),
                ('account_employee_holder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_account', to='employees.Employee')),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='banks.Bank')),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
            },
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='currency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='banks.Currency'),
        ),
        migrations.AddField(
            model_name='bank',
            name='transfer_from_account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_to_bank', to='banks.BankAccount'),
        ),
        migrations.AlterUniqueTogether(
            name='bankaccount',
            unique_together=set([('account_number', 'bank_id')]),
        ),
        migrations.AlterUniqueTogether(
            name='bank',
            unique_together=set([('name', 'branch', 'company_id')]),
        ),
    ]
