# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='banks', to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='bank',
            name='transfer_from_account_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transfer_to_bank', to='banks.BankAccount'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_company_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='account_employee_holder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_account', to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='bank_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='banks.Bank'),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='currency_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='banks.Currency'),
        ),
    ]
