# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-07 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_adminemailcredentials_emailtemplates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmailTemplates',
            new_name='EmailTemplate',
        ),
        migrations.DeleteModel(
            name='AdminEmailCredentials',
        ),
    ]
