# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 18:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180522_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requester',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
