# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-25 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_branches', to='countries.City')),
            ],
            options={
                'verbose_name_plural': 'Branches',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='companies.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='companies.Department')),
            ],
        ),
        migrations.CreateModel(
            name='SubSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('section_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsections', to='companies.Section')),
            ],
        ),
        migrations.AddField(
            model_name='degree',
            name='sub_section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='companies.SubSection'),
        ),
        migrations.AddField(
            model_name='branch',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='companies.Company'),
        ),
        migrations.AlterUniqueTogether(
            name='subsection',
            unique_together=set([('section_id', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together=set([('department_id', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together=set([('branch_id', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='degree',
            unique_together=set([('sub_section_id', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together=set([('company_id', 'name')]),
        ),
    ]
