# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='city_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies_branches', to='countries.City'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='degree',
            name='sub_section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='degrees', to='companies.SubSection'),
        ),
        migrations.AlterField(
            model_name='department',
            name='branch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='companies.Branch'),
        ),
        migrations.AlterField(
            model_name='section',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='companies.Department'),
        ),
        migrations.AlterField(
            model_name='subsection',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subsections', to='companies.Section'),
        ),
    ]
