# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='abscense_days_deduction',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='custom_rule_deduction',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='insurance_deduction',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='taxable_salary',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='taxes_deduction',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='total_taxable_deducted_salary_element',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salary',
            name='total_untaxable_deducted_salary_elements',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
