# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 09:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_auto_20180426_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salary',
            old_name='custom_rule_deduction',
            new_name='custom_rule_amount',
        ),
    ]
