# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-02 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_auto_20180426_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='month',
            field=models.CharField(choices=[('january', 'January'), ('february', 'February'), ('march', 'March'), ('april', 'April'), ('may', 'May'), ('june', 'June'), ('july', 'July'), ('august', 'August'), ('september', 'September'), ('october', 'October'), ('november', 'November'), ('december', 'December')], default=('may', 'May'), max_length=10),
        ),
    ]
