# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_auto_20180514_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxsection',
            name='salary_to',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxsection',
            name='section_execution_sequence',
            field=models.IntegerField(),
        ),
    ]
