# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-19 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_auto_20180619_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxsection',
            name='salary_to',
            field=models.FloatField(default=1000000000000),
        ),
        migrations.AlterField(
            model_name='taxsection',
            name='section_execution_sequence',
            field=models.IntegerField(default=0),
        ),
    ]
