# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-09 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0011_auto_20180703_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
