# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_salary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custompythonrule',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_rules', to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='insurancerule',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insurance_rules', to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='custom_rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='payroll.CustomPythonRule'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='insurance_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='payroll.InsuranceRule'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='tax_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salaries', to='payroll.TaxRule'),
        ),
        migrations.AlterField(
            model_name='salaryelement',
            name='salary_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_elements', to='payroll.Salary'),
        ),
        migrations.AlterField(
            model_name='salaryelement',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_elements', to='payroll.SalaryElementType'),
        ),
        migrations.AlterField(
            model_name='salaryelementtype',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_element_types', to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='taxrule',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_rules', to='companies.Company'),
        ),
        migrations.AlterField(
            model_name='taxsection',
            name='tax_rule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='payroll.TaxRule'),
        ),
    ]
