# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendance_is_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='degree',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='sub_section',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
