# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_auto_20180703_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='overtime_hours',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
