# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-10 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_auto_20180708_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendances', to='employees.Employee'),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='attendance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_offs', to='attendance.Attendance'),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='rule_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_offs', to='attendance.DayOffRule'),
        ),
        migrations.AlterField(
            model_name='dayoffrule',
            name='company_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='day_off_rules', to='companies.Company'),
        ),
    ]
